name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.ESUBALEW_MAC_SSH_PRIVATE_KEY }}  # Access SSH key from secrets.

    - name: Sync Files to Target Server via Jump Server
      run: |
        scp -J esubalew@${{ secrets.JUMP_SERVER_IP }} -r ./ esubalew@${{ secrets.WORDPRESS_PRODUCTION_SERVER_IP }}:/testwp/mailing/