name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.ESUBALEW_MAC_SSH_PRIVATE_KEY }}  # Access SSH key from secrets.

    - name: Add Jump Server to Known Hosts
      run: ssh-keyscan -H ${{ secrets.JUMP_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Add Target Server to Known Hosts
      run: ssh-keyscan -H ${{ secrets.WORDPRESS_PRODUCTION_SERVER_IP }} >> ~/.ssh/known_hosts



    - name: Sync Files to Target Server via Jump Server
      run: |
        scp -J esubalew@${{ secrets.JUMP_SERVER_IP }} -r * esubalew@${{ secrets.WORDPRESS_PRODUCTION_SERVER_IP }}:/var/www/wordpress/wp-content/plugins/mp-mailing-list